import { NextResponse } from "next/server";
import { generateText } from "ai";

export const runtime = "nodejs";

const MODEL = "google/gemini-2.5-flash";

// Sensible, generic wellbeing actions used if the gateway is unavailable.
const FALLBACK = [
  "Salí a caminar 15 minutos al aire libre hoy.",
  "Escribile a alguien con quien quieras reconectar.",
  "Anotá 3 cosas que agradecés antes de dormir.",
  "Reservá 10 minutos sin pantallas para respirar.",
];

/**
 * Suggest a few small, actionable wellbeing items for the week, generated by
 * an LLM via the Vercel AI Gateway. Input is a compact, non-sensitive summary
 * (no raw journal text). Falls back to a generic list on any error.
 */
export async function POST(req: Request) {
  try {
    const { context } = (await req.json()) as { context?: unknown };
    if (typeof context !== "string" || !context.trim() || context.length > 2000) {
      return NextResponse.json({ error: "invalid context" }, { status: 400 });
    }

    if (!process.env.AI_GATEWAY_API_KEY) {
      return NextResponse.json({ items: FALLBACK, source: "fallback" });
    }

    const { text } = await generateText({
      model: MODEL,
      temperature: 0.7,
      prompt:
        "Sos un coach de bienestar argentino, cálido y concreto. En base a esta semana de una persona, sugerí 4 acciones chiquitas, realizables hoy o esta semana, y conectadas a sus temas (no genéricas). Cada una en una frase corta, en español rioplatense, empezando con un verbo. Respondé SOLO con un array JSON de strings, sin texto extra.\n\n" +
        context,
    });

    let items: string[] = [];
    try {
      const match = text.match(/\[[\s\S]*\]/);
      const parsed = JSON.parse(match ? match[0] : text);
      if (Array.isArray(parsed)) {
        items = parsed.filter((i) => typeof i === "string").slice(0, 5);
      }
    } catch {
      /* parse failed -> fallback below */
    }

    if (items.length === 0) {
      return NextResponse.json({ items: FALLBACK, source: "fallback" });
    }
    return NextResponse.json({ items, source: "ai" });
  } catch (err) {
    console.error("recommendations failed:", err);
    return NextResponse.json({ items: FALLBACK, source: "fallback" });
  }
}
