import { NextResponse } from "next/server";
import { generateText } from "ai";

export const runtime = "nodejs";

const MODEL = "google/gemini-2.5-flash";

type Locale = "es" | "en";

// Sensible, generic wellbeing actions used if the gateway is unavailable.
const FALLBACK: Record<Locale, string[]> = {
  es: [
    "Salí a caminar 15 minutos al aire libre hoy.",
    "Escribile a alguien con quien quieras reconectar.",
    "Anotá 3 cosas que agradecés antes de dormir.",
    "Reservá 10 minutos sin pantallas para respirar.",
  ],
  en: [
    "Take a 15-minute walk outside today.",
    "Text someone you'd like to reconnect with.",
    "Write down 3 things you're grateful for before bed.",
    "Carve out 10 screen-free minutes to breathe.",
  ],
};

const PROMPT: Record<Locale, string> = {
  es: `Sos un coach de bienestar argentino, cálido y concreto. Abajo están los registros de la semana de una persona (ánimo 1-10 + qué compartió + temas).

Tu tarea: sugerí 3 o 4 acciones chiquitas y realizables, MUY conectadas a SUS registros puntuales (no genéricas):
- Para lo que la pone mal, proponé algo que la ayude con ESO específico (ej: si discutió con su pareja, retomar la charla desde lo que siente; si se sintió sola, un gesto concreto para reconectar con alguien).
- Para lo que la hace bien, proponé algo que lo potencie o lo repita (ej: si una cena con amigos o un rato con su mascota la recargaron, buscar más de eso).
Referenciá lo concreto que contó. Cada acción: una frase corta, en español rioplatense, empezando con un verbo.

SEGURIDAD (importante): si en los registros hay señales de angustia seria, desesperanza, autolesión o riesgo, NO des tips casuales. Devolvé UN SOLO ítem, cálido, que la invite a hablar con un profesional y mencioná la línea 135 (Argentina, prevención del suicidio).

Respondé SOLO con un array JSON de strings, sin texto extra.

`,
  en: `You are a warm, concrete wellbeing coach. Below are this week's logs from a person (mood 1-10 + what they shared + themes).

Your task: suggest 3 or 4 small, doable actions, TIGHTLY tied to THEIR specific logs (no generic tips):
- For what's weighing on them, propose something that helps with THAT specifically (e.g. if they had a fight with their partner, picking the conversation back up from what they feel; if they felt lonely, one concrete gesture to reconnect).
- For what lifts them up, propose something that amplifies or repeats it (e.g. if a dinner with friends or time with their pet recharged them, find more of that).
Reference the concrete thing they shared. Each action: one short sentence, natural English, starting with a verb.

SAFETY (important): if the logs show serious distress, hopelessness, self-harm or risk, do NOT give casual tips. Return ONE warm item that invites them to talk to a professional and mention crisis support (e.g. 988 in the US, or 135 in Argentina).

Respond with ONLY a JSON array of strings, no extra text.

`,
};

/**
 * Suggest a few small, actionable wellbeing items for the week, generated by
 * an LLM via the Vercel AI Gateway. Input is a compact, non-sensitive summary
 * (no raw journal text). Falls back to a generic list on any error.
 */
export async function POST(req: Request) {
  try {
    const body = (await req.json()) as { context?: unknown; locale?: unknown };
    const context = body.context;
    const locale: Locale = body.locale === "en" ? "en" : "es";

    if (typeof context !== "string" || !context.trim() || context.length > 2000) {
      return NextResponse.json({ error: "invalid context" }, { status: 400 });
    }

    if (!process.env.AI_GATEWAY_API_KEY) {
      return NextResponse.json({ items: FALLBACK[locale], source: "fallback" });
    }

    const { text } = await generateText({
      model: MODEL,
      temperature: 0.7,
      prompt: PROMPT[locale] + context,
    });

    let items: string[] = [];
    try {
      const match = text.match(/\[[\s\S]*\]/);
      const parsed = JSON.parse(match ? match[0] : text);
      if (Array.isArray(parsed)) {
        items = parsed.filter((i) => typeof i === "string").slice(0, 5);
      }
    } catch {
      /* parse failed -> fallback below */
    }

    if (items.length === 0) {
      return NextResponse.json({ items: FALLBACK[locale], source: "fallback" });
    }
    return NextResponse.json({ items, source: "ai" });
  } catch (err) {
    console.error("recommendations failed:", err);
    return NextResponse.json({ items: FALLBACK.es, source: "fallback" });
  }
}
